import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const migrationsDir = path.resolve(__dirname, '../electron/backend/persistence/migrations');
const outputPath = path.resolve(__dirname, '../electron/backend/persistence/generatedMigrations.ts');
const checkOnly = process.argv.includes('--check');

function encodeTemplateLiteral(source: string): string {
    return source.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function loadMigrations(): Array<{ name: string; sql: string }> {
    const filenames = readdirSync(migrationsDir)
        .filter((filename) => filename.endsWith('.sql'))
        .sort((left, right) => left.localeCompare(right));

    return filenames.map((filename) => {
        const migrationPath = path.join(migrationsDir, filename);
        const sql = readFileSync(migrationPath, 'utf8').trimEnd();
        return { name: filename, sql };
    });
}

function buildOutput(migrations: Array<{ name: string; sql: string }>): string {
    const body = migrations
        .map(
            (migration) =>
                `    {\n` +
                `        name: '${migration.name}',\n` +
                `        sql: \`\n${encodeTemplateLiteral(migration.sql)}\n\`,\n` +
                `    },`
        )
        .join('\n');

    return [
        '// Auto-generated by scripts/generate-migrations.ts. Do not edit manually.',
        '',
        'export interface RuntimeSqlMigration {',
        '    name: string;',
        '    sql: string;',
        '}',
        '',
        'export const runtimeSqlMigrations: RuntimeSqlMigration[] = [',
        body,
        '];',
        '',
    ].join('\n');
}

const migrations = loadMigrations();
const nextContent = buildOutput(migrations);
const currentContent = existsSync(outputPath) ? readFileSync(outputPath, 'utf8') : null;

if (checkOnly) {
    if (currentContent !== nextContent) {
        console.error('[generate-migrations] generatedMigrations.ts is stale. Run `pnpm generate:migrations`.');
        process.exit(1);
    }

    console.log('[generate-migrations] generatedMigrations.ts is up to date.');
    process.exit(0);
}

mkdirSync(path.dirname(outputPath), { recursive: true });
writeFileSync(outputPath, nextContent, 'utf8');
console.log(`[generate-migrations] wrote ${path.relative(path.resolve(__dirname, '..'), outputPath)}`);
