// Auto-generated by scripts/generate-migrations.ts. Do not edit manually.

export interface RuntimeSqlMigration {
    name: string;
    sql: string;
}

export const runtimeSqlMigrations: RuntimeSqlMigration[] = [
    {
        name: '001_init.sql',
        sql: `
CREATE TABLE IF NOT EXISTS schema_migrations (
    name TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS profiles (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS providers (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    supports_byok INTEGER NOT NULL CHECK (supports_byok IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS provider_models (
    id TEXT PRIMARY KEY,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_provider_models_provider_id ON provider_models(provider_id);

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    scope TEXT NOT NULL,
    kind TEXT NOT NULL,
    run_status TEXT NOT NULL,
    pending_completion_run_id TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS runs (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    prompt TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_runs_session_id_created_at ON runs(session_id, created_at DESC);

CREATE TABLE IF NOT EXISTS permissions (
    id TEXT PRIMARY KEY,
    policy TEXT NOT NULL,
    resource TEXT NOT NULL,
    decision TEXT NOT NULL,
    rationale TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_permissions_decision_created_at ON permissions(decision, created_at);

CREATE TABLE IF NOT EXISTS settings (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_settings_profile_key ON settings(profile_id, key);

CREATE TABLE IF NOT EXISTS runtime_events (
    sequence INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id TEXT NOT NULL UNIQUE,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_runtime_events_sequence ON runtime_events(sequence);

CREATE TABLE IF NOT EXISTS tools_catalog (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    description TEXT NOT NULL,
    permission_policy TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS mcp_servers (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    auth_mode TEXT NOT NULL,
    connection_state TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
`,
    },
    {
        name: '002_core_runtime.sql',
        sql: `
CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,
    scope TEXT NOT NULL,
    title TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS threads (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_threads_conversation_id_updated_at
    ON threads(conversation_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS tags (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS thread_tags (
    thread_id TEXT NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
    tag_id TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (thread_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_thread_tags_tag_id ON thread_tags(tag_id);

CREATE TABLE IF NOT EXISTS diffs (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    run_id TEXT NULL REFERENCES runs(id) ON DELETE SET NULL,
    summary TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_diffs_session_id_created_at
    ON diffs(session_id, created_at DESC);
`,
    },
    {
        name: '003_p1c_runtime_foundation.sql',
        sql: `
ALTER TABLE sessions
    ADD COLUMN workspace_fingerprint TEXT NULL;

CREATE INDEX IF NOT EXISTS idx_sessions_workspace_fingerprint
    ON sessions(workspace_fingerprint);

ALTER TABLE conversations
    ADD COLUMN workspace_fingerprint TEXT NULL;

CREATE INDEX IF NOT EXISTS idx_conversations_workspace_fingerprint
    ON conversations(workspace_fingerprint);

INSERT OR IGNORE INTO profiles (id, name, created_at, updated_at)
VALUES (
    'profile_local_default',
    'Local Default',
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
);

INSERT OR IGNORE INTO profiles (id, name, created_at, updated_at)
SELECT
    CASE
        WHEN profile_id = '__global__' THEN 'profile_local_default'
        ELSE profile_id
    END AS id,
    'Migrated Profile',
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM settings;

DROP INDEX IF EXISTS idx_settings_profile_key;

CREATE TABLE IF NOT EXISTS settings_v2 (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

INSERT INTO settings_v2 (id, profile_id, key, value_json, updated_at)
SELECT
    id,
    CASE
        WHEN profile_id = '__global__' THEN 'profile_local_default'
        ELSE profile_id
    END AS profile_id,
    key,
    value_json,
    updated_at
FROM settings;

DROP TABLE settings;

ALTER TABLE settings_v2
    RENAME TO settings;

CREATE UNIQUE INDEX IF NOT EXISTS idx_settings_profile_key
    ON settings(profile_id, key);
`,
    },
];
